# 3. Definition of Arrays

### Define an Array

In [1]:
array1 = [1, 2, 3, 4, 5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

### It is possible to define an array of mixed numbers and letters.

In [2]:
array2 = [1, 2, "three", 4, 5]

5-element Array{Any,1}:
 1       
 2       
  "three"
 4       
 5       

#### * String types must be enclosed in " ".

### Acquisition of element

In [3]:
array1[3]

3

In [4]:
array2[3]

"three"

In [5]:
array1[0]

BoundsError: BoundsError: attempt to access 5-element Array{Int64,1} at index [0]

#### * Index start from 1, specifying 0 results in an error.

### Push and Pop

In [6]:
push!(array1, 6)
println(array1)

[1, 2, 3, 4, 5, 6]


In [7]:
pop!(array1)
println(array1)

[1, 2, 3, 4, 5]


### Update element

In [8]:
array2[1] = "one"
array2

5-element Array{Any,1}:
  "one"  
 2       
  "three"
 4       
 5       

# 4. Multidimensional Array

In [9]:
array_2d = [[1, 2, 3, 4, 5],["one", 2, "three", 4, 5]]

2-element Array{Array{Any,1},1}:
 [1, 2, 3, 4, 5]          
 ["one", 2, "three", 4, 5]

### Array using random numbers

In [10]:
rand(5, 2)

5×2 Array{Float64,2}:
 0.0937879  0.121352
 0.396082   0.198874
 0.486931   0.670605
 0.772202   0.701368
 0.374351   0.260145

### Functions related to Array

In [11]:
println(zeros(5)) # 1d array

[0.0, 0.0, 0.0, 0.0, 0.0]


In [12]:
println(zeros(5, 2)) # multidimension array

[0.0 0.0; 0.0 0.0; 0.0 0.0; 0.0 0.0; 0.0 0.0]


In [13]:
println(zeros(Int8, 5, 2)) # type specification

Int8[0 0; 0 0; 0 0; 0 0; 0 0]


In [14]:
println(ones(5)) # 1d array

[1.0, 1.0, 1.0, 1.0, 1.0]


In [15]:
println(ones(5, 2)) # multidimension array

[1.0 1.0; 1.0 1.0; 1.0 1.0; 1.0 1.0; 1.0 1.0]


In [16]:
println(ones(Float64, 5, 2)) # type specification

[1.0 1.0; 1.0 1.0; 1.0 1.0; 1.0 1.0; 1.0 1.0]


In [17]:
fill(12.3, (5, 2))

5×2 Array{Float64,2}:
 12.3  12.3
 12.3  12.3
 12.3  12.3
 12.3  12.3
 12.3  12.3

### Function to get array information

In [18]:
ones_2d = ones(5, 3)

5×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [19]:
ndims(ones_2d) # Get array dimention

2

In [20]:
indices(ones_2d)

UndefVarError: UndefVarError: indices not defined

In [21]:
length(ones_2d) # Count the number of elements

15