# In Python, import Numpy package is required to handle arrays

### 1D Array

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [2]:
print(a)

[1 2 3 4 5]


In [3]:
type(a)

numpy.ndarray

In [4]:
a.shape

(5,)

In [5]:
a[1] # elements start at 0. In Julia start at 1

2

In [6]:
a[0] = 10
a

array([10,  2,  3,  4,  5])

### 2D Array

In [7]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
type(b)

numpy.ndarray

In [9]:
b.shape

(3, 3)

In [10]:
b[1,2] # elements start at 0. In Julia start at 1

6

## Reshape

In [11]:
c1 = np.array((0, 1, 2, 3, 4, 5))
c1

array([0, 1, 2, 3, 4, 5])

In [12]:
c2 = c1.reshape((2, 3)) # Array name.reshape(row, column)
c2

array([[0, 1, 2],
       [3, 4, 5]])